#!/usr/bin/env zsh
set -euo pipefail

# publish_website.sh
# Builds, exports (static) the Next.js site and publishes to GitHub Pages using gh-pages.
# Usage: ./publish_website.sh

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT_DIR"

echo "[publish_website] Working directory: $ROOT_DIR"

# Install dependencies
echo "[publish_website] Installing dependencies..."
npm install

# Build the Next.js site
echo "[publish_website] Building site (next build)..."
npm run build

# Export static HTML (explicit) to out/
# Some Next versions require `next export`; running explicitly is safe.
echo "[publish_website] Exporting static site to out/ (npx next export)..."
OUT_DIR="out"

# Older Next.js versions used `next export`. Newer versions (with output: 'export') perform export during `next build`.
# Only run `npx next export` when `out/` is not already present and `next export` is supported.
if [ -d "$OUT_DIR" ]; then
  echo "[publish_website] Found $OUT_DIR after build — skipping explicit 'next export'."
else
  echo "[publish_website] $OUT_DIR not found after build. Attempting to run 'npx next export' (may fail on newer Next.js versions)..."
  if npx next export; then
    echo "[publish_website] next export completed and created $OUT_DIR"
  else
    echo "[publish_website] 'npx next export' failed or is not supported by this Next.js version."
    echo "[publish_website] If you're using Next with 'output: export' the static files should already have been generated by 'next build'."
    echo "[publish_website] Please check the build output and ensure there's an export directory (usually 'out/') before re-running this script. Aborting."
    exit 1
  fi
fi
DEPLOY_DIR="deploy-gh-pages"

# Prepare deploy directory
if [ -d "$DEPLOY_DIR" ]; then
  echo "[publish_website] Removing existing $DEPLOY_DIR"
  rm -rf "$DEPLOY_DIR"
fi

if [ ! -d "$OUT_DIR" ]; then
  echo "[publish_website] ERROR: expected $OUT_DIR to exist after export. Aborting."
  exit 1
fi

mv "$OUT_DIR" "$DEPLOY_DIR"
# Prevent GitHub Pages from treating files as Jekyll
touch "$DEPLOY_DIR/.nojekyll"

# Publish using gh-pages
echo "[publish_website] Publishing $DEPLOY_DIR with gh-pages..."
npx gh-pages -d "$DEPLOY_DIR" --dotfiles

echo "[publish_website] Done."
